#!/bin/bash

numberOfDisks=5
sizeOfDisksGB=7GB
raidLevel=0
deviceName=md127
mountPoint=/data
part=(b c d e f g h i j k l m n o p q r s t u v w x y z);

for (( COUNT=1 ; COUNT <= $numberOfDisks ; COUNT++ )) ; do
	echo parted --script /dev/sd${part[$COUNT]} "mklabel gpt mkpart primary 1MiB $sizeOfDisksGB"
	#echo ${part[$COUNT]}
done;

for (( COUNT2=1 ; COUNT2 <= $numberOfDisks ; COUNT2++ )) ; do
	while [ ! -e "/dev/sd${part[$COUNT2]}" ]; do sleep 1; done
done;

mdadm --create $deviceName --level $raidLevel --raid-devices $numberOfDisks /dev/sd{c,d,e,f,g,h,i,j}

mkfs -t ext4 $deviceName

mkdir $mountPoint

uuid=$(blkid -o value -s UUID $deviceName)
echo "UUID=$uuid     $mountPoint   ext4    defaults,discard,nofail        0 2" >> /etc/fstab
mount -a
echo "bootdegraded=true" >> /etc/default/grub
cp -a /boot/grub2/grub.cfg /boot/grub2/grub.cfg.bak
grub2-mkconfig -o /boot/grub2/grub.cfg
